vector = c(1, 2, 3, 4, 5)
factor = factor(c("ani", "basu", "raju"))
array = array(1:12, dim = c(3, 4))
list = list(vector = vector, factor = factor, array = array)
print("Original list:")
print(list)
list$array = array(13:24, dim = c(3, 4))
print("Updated list:")
print(list)